---
name: RELEASE

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    paths:
      - builds/**

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  BUILD:
    uses: ./.github/workflows/rw-composite-buildx.yaml
    with:
      src_path: 'builds'
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}