# ---
# name: DEPLOY

# on:
#   push:
#     branches:
#     - main
#   pull_request:
#     branches:
#     - main
#     paths:
#       - src/**

# permissions:
#   id-token: write # This is required for requesting the JWT
#   contents: read  # This is required for actions/checkout

# jobs:
#   DEPLOY:
#     uses: ./.github/workflows/rw-composite-helm.yaml
#     with:
#       src_path: 'src'